cronos_777-1:
  accounts:
    - coins: "10000000000000000000000basetcro"
      mnemonic: "${COMMUNITY_MNEMONIC}"
      name: "community"
    - coins: "20000000000000000000000basetcro"
      mnemonic: "${SIGNER1_MNEMONIC}"
      name: "signer1"
    - coins: "30000000000000000000000basetcro"
      mnemonic: "${SIGNER2_MNEMONIC}"
      name: "signer2"
  app-config:
    json-rpc:
      address: "0.0.0.0:{EVMRPC_PORT}"
      block-range-cap: 10000
      feehistory-cap: 100
      logs-cap: 10000
      ws-address: "0.0.0.0:{EVMRPC_PORT_WS}"
    minimum-gas-prices: "5000000000000basetcro"
  cmd: "cronosd"
  genesis:
    app_state:
      cronos:
        params:
          cronos_admin: "${CRONOS_ADMIN}"
          enable_auto_deployment: true
          ibc_cro_denom: "${IBC_CRO_DENOM}"
      evm:
        params:
          evm_denom: "basetcro"
      feemarket:
        params:
          no_base_fee: true
      gov:
        deposit_params:
          max_deposit_period: "10s"
          min_deposit:
            - amount: "1"
              denom: "basetcro"
        voting_params:
          voting_period: "10s"
      transfer:
        params:
          receive_enabled: true
          send_enabled: true
    consensus_params:
      block:
        max_bytes: "1048576"
        max_gas: "81500000"
  validators:
    - coins: "1000000000000000000stake,10000000000000000000000basetcro"
      mnemonic: "${VALIDATOR1_MNEMONIC}"
      staked: "1000000000000000000stake"
    - coins: "1000000000000000000stake,10000000000000000000000basetcro"
      mnemonic: "${VALIDATOR2_MNEMONIC}"
      staked: "1000000000000000000stake"
dotenv: "../../scripts/.env"
