dotenv: ../../scripts/.env
cronos_777-1:
  cmd: cronosd
  start-flags: "--trace"
  account-prefix: "crc"
  coin-type: 60
  app-config:
    minimum-gas-prices: 0basetcro
    index-events:
      - ethereum_tx.ethereumTxHash
    json-rpc:
      address: "0.0.0.0:{EVMRPC_PORT}"
      ws-address: "0.0.0.0:{EVMRPC_PORT_WS}"
      api: "eth,net,web3,debug,cronos"
  validators:
    - coins: 1000000000000000000stake,10000000000000000000000basetcro
      staked: 1000000000000000000stake
      mnemonic: ${VALIDATOR1_MNEMONIC}
    - coins: 1000000000000000000stake,10000000000000000000000basetcro
      staked: 1000000000000000000stake
      mnemonic: ${VALIDATOR2_MNEMONIC}
  accounts:
    - name: community
      coins: 10000000000000000000000basetcro
      mnemonic: ${COMMUNITY_MNEMONIC}
    - name: relayer
      coins: 20000000000000000000000basetcro
      mnemonic: ${SIGNER1_MNEMONIC}
    - name: signer2
      coins: 30000000000000000000000basetcro
      mnemonic: ${SIGNER2_MNEMONIC}

  genesis:
    consensus_params:
      block:
        max_bytes: "1048576"
        max_gas: "81500000"
    app_state:
      evm:
        params:
          evm_denom: basetcro
          min_gas_multiplier: "0"
      cronos:
        params:
          cronos_admin: ${CRONOS_ADMIN}
          enable_auto_deployment: true
          ibc_cro_denom: ${IBC_CRO_DENOM}
      gov:
        voting_params:
          voting_period: "10s"
        deposit_params:
          max_deposit_period: "10s"
          min_deposit:
            - denom: "basetcro"
              amount: "1"
      transfer:
        params:
          receive_enabled: true
          send_enabled: true
      feemarket:
        params:
          no_base_fee: false
          base_fee: "100000000000"
chainmain-1:
  cmd: chain-maind
  start-flags: "--trace"
  account-prefix: "cro"
  app-config:
    minimum-gas-prices: 500basecro
  validators:
    - coins: 2234240000000000000cro
      staked: 10000000000000cro
      mnemonic: ${VALIDATOR1_MNEMONIC}
      base_port: 26800
    - coins: 987870000000000000cro
      staked: 20000000000000cro
      mnemonic: ${VALIDATOR2_MNEMONIC}
      base_port: 26810
#   min_self_delegation: 10000000  # 0.1cro
  accounts:
    - name: community
      coins: 10000000000000cro
      mnemonic: ${COMMUNITY_MNEMONIC}
    - name: relayer
      coins: 10000000000000cro
      mnemonic: ${SIGNER1_MNEMONIC}
    - name: signer2
      coins: 10000000000000cro
      mnemonic: ${SIGNER2_MNEMONIC}
  genesis:
    app_state:
      staking:
        params:
          unbonding_time: "1814400s"
      gov:
        voting_params:
          voting_period: "1814400s"
        deposit_params:
          max_deposit_period: "1814400s"
          min_deposit:
            - denom: "basecro"
              amount: "10000000"
      transfer:
        params:
          receive_enabled: true
          send_enabled: true
      interchainaccounts:
        host_genesis_state:
          params:
            allow_messages: ["/cosmos.bank.v1beta1.MsgSend"]
relayer:
  rest:
    enabled : true
    host    : "127.0.0.1"
    port    : 3000
  chains:
    - id: cronos_777-1
      address_type:
        derivation: ethermint
        proto_type:
          pk_type: "/ethermint.crypto.v1.ethsecp256k1.PubKey"
      gas_price:
        price: 10000000000000
        denom: basetcro
    - id: chainmain-1
      gas_price: 
        price: 1000000
        denom: basecro
