#!/bin/bash

set +e
cd "$(dirname "$0")"

# explicitly set a short TMPDIR to prevent path too long issue on macosx
export TMPDIR=/tmp

files=("cronos-devnet" "cronos-experimental-devnet")
length=${#files[@]}
for (( i=0; i<${length}; i++ ))
do
    echo "generating "${files[$i]}".yaml"
    jsonnet -S ${files[$i]}.jsonnet -o ${files[$i]}.yaml
done
